# Generated by Django 3.2 on 2025-04-25 21:26

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_comment_unique_author_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Основной текст', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[api.validators.validate_score_range], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(help_text='Основной текст', verbose_name='Текст'),
        ),
    ]
