# Generated by Django 3.2 on 2025-04-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20250425_2126'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_author_review',
        ),
    ]
