# Generated by Django 3.2 on 2025-04-25 21:26

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20250423_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(db_index=True, validators=[api.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
